In [17]:
result_df = pd.read_csv("result1.csv", encoding='utf-8-sig')

In [18]:
result_df

,구분,Jan.,Feb.,Mar.,Apr.,May,Jun.,Jul.,Aug.,Sep.,Oct.,Nov.,Dec.,Total,sales_type,age,year
0,Audi - Q2 35 TDI,1,0,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
1,BMW - 218d Gran Coupe,0,1,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
2,BMW - 520,1,0,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
3,Bentley - Continental GT V8,0,1,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
4,Honda - CR-V Hybrid,0,0,0,1,0,0,0,0,0,0,0,0,1,개인,~19,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15299,Volvo - XC60 B5 AWD,0,0,0,28,0,0,0,0,0,0,0,0,28,법인,70~,2021
15300,Volvo - XC60 B6 AWD,0,0,9,16,0,0,0,0,0,0,0,0,25,법인,70~,2021
15301,Volvo - XC60 T8 AWD,78,112,45,16,0,0,0,0,0,0,0,0,251,법인,70~,2021
15302,Volvo - XC90 B6 AWD,0,0,20,22,0,0,0,0,0,0,0,0,42,법인,70~,2021
15303,Volvo - XC90 T8 AWD,49,45,43,27,0,0,0,0,0,0,0,0,164,법인,70~,2021

In [19]:
result_df.rename(columns={'Jan.': '1', 'Feb.': '2', 'Mar.':'3', 'Apr.':'4', 'May':'5', 'Jun.':'6',
                 'Jul.':'7', 'Aug.':'8', 'Sep.':'9', 'Oct.':'10', 'Nov.':'11', 'Dec.':'12'}, inplace=True)

In [20]:
result_df

,구분,1,2,3,4,5,6,7,8,9,10,11,12,Total,sales_type,age,year
0,Audi - Q2 35 TDI,1,0,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
1,BMW - 218d Gran Coupe,0,1,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
2,BMW - 520,1,0,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
3,Bentley - Continental GT V8,0,1,0,0,0,0,0,0,0,0,0,0,1,개인,~19,2020
4,Honda - CR-V Hybrid,0,0,0,1,0,0,0,0,0,0,0,0,1,개인,~19,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15299,Volvo - XC60 B5 AWD,0,0,0,28,0,0,0,0,0,0,0,0,28,법인,70~,2021
15300,Volvo - XC60 B6 AWD,0,0,9,16,0,0,0,0,0,0,0,0,25,법인,70~,2021
15301,Volvo - XC60 T8 AWD,78,112,45,16,0,0,0,0,0,0,0,0,251,법인,70~,2021
15302,Volvo - XC90 B6 AWD,0,0,20,22,0,0,0,0,0,0,0,0,42,법인,70~,2021
15303,Volvo - XC90 T8 AWD,49,45,43,27,0,0,0,0,0,0,0,0,164,법인,70~,2021

In [21]:
result_df_tp = result_df.drop(columns=(["sales_type", "age", "year"]))

In [25]:
result_df_tp_jan = result_df_tp[["구분", "1"]]

In [54]:
test1_pd = pd.DataFrame(columns=("Model", "월"))

In [76]:
tes = list(result_df_tp[["구분", "1"]])

In [73]:
tp = []
for n in  result_df_tp[["구분", "1"]].values():
    data = n
    tp.append(data)

TypeError: 'numpy.ndarray' object is not callable

In [72]:
tp

['구분', '1']

In [70]:
len(result_df_tp[["구분", "1"]])

15304